### ISSUE TITLE
linting tool

### ISSUE THREAD

**Issue by Guria** [cerebral-legacy/discussion#1]
We need final decission on linting tools / rules across oraganisation repositories.
I have suggested zero-configuration variant [standard](npmjs.com/package/standard) but it includes `no semicolons` rule (authors sais [that](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [it's](http://inimino.org/~inimino/blog/javascript_semicolons) [fine](https://www.youtube.com/watch?v=gsfbh17Ax9I)).
Another suggestion was to use [semistandard](npmjs.com/package/semistandard)(`standard` but with semicolons) as alternative.
Third option could be shareable config package for `eslint`.

cc @cerebral/collaborators and others with reasonable opinions.

**Comment by garth** [comment]
I think that an eslint configuration that can be shared across all cerebral projects would be a good idea.

``` js
// example package.json
{
  "scripts": {
    "lint": "eslint --config node_modules/cerebral-lint/.eslintrc ."
  }
}
```

**Comment by christianalfoni** [comment]
Yeah, I like @garth suggestion. Gives most flexibility. When it comes to actual rules I do not have any opinion. The codebase is not really that huge, so not much work conforming to anything really. But we might have some fun linting discussions. Maybe we could have like "beer lint-pong"? One team wants one rule and somebody an other and we play beer pong on it? :-)

It really just not matter. We just have to choose one. I suggest we hook in the rules from "standard" and @garth can review with suggested changes. Then we just tell people: "Meet up at that time, we will vote". Those who does not meet, wont have a say.

Later we can have "beer lint-pong" competition at cerebral-conf, for a second review ;-)

**Comment by Guria** [comment]
I also don't have opinion on rules. I can adapt to any. I've suggested `standard` because met some notable count of projects using it and was excited not to use custom rule set but just one command.
So we have `easy to setup` vs `comfort with editors`.

**Comment by christianalfoni** [comment]
You know, I think the person making the effort on bringing linting into the projects should decide. If you want to make that effort @Guria, you make the choice. As I think we all agree, we want linting, the rules does not matter... it is the consistency we want :-)

**Comment by christianalfoni** [comment]
I am extremely happy with standards... or anything else ;-)

**Comment by garth** [comment]
Are there any stats on standard and semi standard usage?

**Comment by Guria** [comment]
Only npm's one I think.

**Comment by Guria** [comment]
BTW `standard` has [plenty plugins for editors](https://github.com/feross/standard#text-editor-plugins)

**Comment by garth** [comment]
yes, I tried some editor plugins. I guess I need to switch from sublime to atom, just that atom is so amazingly slow.

So we are going with standard?

**Comment by Guria** [comment]
I suppose. If there is no any blocker.

**Comment by Guria** [comment]
https://github.com/cerebral/discussion/wiki/Linting
